name:        followmon
version:     0.1.0.0
synopsis:    Telegram bot that monitors Twitter followers
description: See README at <https://github.com/chuahou/followmon#readme>.
category:    Web
github:      chuahou/followmon
maintainer:  Chua Hou <human+github@chuahou.dev>

ghc-options:
    - -Wall
    - -fwarn-incomplete-uni-patterns
    - -fwarn-incomplete-record-updates
    - -static

default-extensions:
    - ImportQualifiedPost
    - LambdaCase
    - OverloadedRecordDot
    - OverloadedStrings
    - QuasiQuotes
    - TupleSections

dependencies:
    - base >= 4.16 && < 5
    - aeson ^>= 2.1.1.0
    - containers ^>= 0.6.5.1
    - dhall ^>= 1.41.2
    - http-conduit ^>= 2.3.8
    - string-interpolate ^>= 0.3.2.0
    - time ^>= 1.11.1.1
    - transformers ^>= 0.5.6.2
    - utf8-string ^>= 1.0.2

executable:
    main:        Main.hs
    source-dirs: exe
    ghc-options: -threaded
